image: node:10.15.0
  
pipelines:
  # default:
  #   - step:
  #       name: Build and test
  #       script:
  #         - npm install
  #         - node node-tasks.js
  branches:
    master:
      - step:
          name: Deploy
          script:
            - npm install
            - node node-tasks.js